### ISSUE TITLE
ubuntu amd64 rt为必填项,请输入refreshToken

### ISSUE THREAD

**Issue by firstuanl** [LinkLeong/go-aliyundrive-webdav#11]
已输refreshToken，还是提示没rt，1.0.3;1.0.4;

firefox，vivdia

java版的正常

**Comment by LinkLeong** [comment]
![image](https://user-images.githubusercontent.com/13556972/140639309-7059ce06-7f10-420f-8544-2de5970209e4.png)
经过测试目前未找到问题.

**Comment by LinkLeong** [comment]
好的,我尽快处理

**Comment by firstuanl** [comment]
`./webdav -rt="b0e0e这里省略4e9899d72c" -v
rt为必填项,请输入refreshToken
`
`uname -a
Linux power 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by LinkLeong** [comment]
好的  我已经找到问题了,晚上会进行修复.

**Comment by LinkLeong** [comment]
@firstuanl 更新了1.0.5
可以试试
有问题在反馈

**Comment by firstuanl** [comment]
你好，谢谢，晚上才能试试

PS：token好像过几天会变动，有没更好的方式解决。

PS2：之前都 没接网盘挂载这操作，顺便 请教个问题，
用davfs挂载，怎解决只能用root，且只能读。
或者有其他更好的方式 ？

**Comment by LinkLeong** [comment]
问题1:token在手动填的时候是会变的,程序运行不停止的情况下不用管的,程序会自动更新这个token
问题2:davfs没使用过,后面我会尝试使用一下,建议使用rclone.

**Comment by firstuanl** [comment]
谢谢。
