### ISSUE TITLE
webdav上传文件是要把上传的文件复制到执行目录再上传吗

### ISSUE THREAD

**Issue by daofeng2015** [LinkLeong/go-aliyundrive-webdav#14]
是把要上传的文件复制到执行目录,重命名为aaa.png再上传的吗?
还有建议支持保存日志的功能,而且这个项目好像也没用到协程

**Comment by LinkLeong** [comment]
第一个问题没太清楚,
第二个问题保存日志功能可以考虑
第三个问题没办法用携程,网盘的上传有顺序,所以只能循环上传.

**Comment by daofeng2015** [comment]
> 第一个问题没太清楚, 第二个问题保存日志功能可以考虑 第三个问题没办法用携程,网盘的上传有顺序,所以只能循环上传.

第一:就是你要上传的文件首先会复制到二进制所在的目录下,然后再上传,是不是这样的?
第三:首先你发送需要上传的文件的信息,然后服务器会返回一个数组,数组里面有个序号和单独的上传服务器地址,你只需要把你需要上传的文件切片发送到对应的地址,上传完成后post一下服务器,数据上传完成,最好再调用保存到网盘的api就行了,这就是单文件上传的逻辑

**Comment by LinkLeong** [comment]
> > 第一个问题没太清楚, 第二个问题保存日志功能可以考虑 第三个问题没办法用携程,网盘的上传有顺序,所以只能循环上传.
> 
> 第一:就是你要上传的文件首先会复制到二进制所在的目录下,然后再上传,是不是这样的?
> 第三:首先你发送需要上传的文件的信息,然后服务器会返回一个数组,数组里面有个序号和单独的上传服务器地址,你只需要把你需要上传的文件切片发送到对应的地址,上传完成后post一下服务器,数据上传完成,最好再调用保存到网盘的api就行了,这就是单文件上传的逻辑

第一个问题:没有复制到临时目录，直接读取了映射目录里的文件。
第三个问题:是这个逻辑，但上传文件阿里那边要求是顺序的上传，这个问题我明天重新检查一下，给你更准确的回答

**Comment by daofeng2015** [comment]
不需要按顺序上传,主要是按分片的,那为啥我上传会出现aaa.png这个文件呢?

**Comment by LinkLeong** [comment]
aaa.png可能是我测试的代码没移除赶紧,这个我在检查一下.
第三个问题:
在上传文件的步骤
1.发送需要上传的文件信息给阿里网盘   返回   分片上传文件的列表
2.并发上传会导致文件乱码(顺序上传没有问题)
3.发送文件上传完成接口

猜想:阿里网盘应该是对每次的文件端进行累加,而不是等文件片段上传完一起拼接

**Comment by daofeng2015** [comment]
> aaa.png可能是我测试的代码没移除赶紧,这个我在检查一下. 第三个问题: 在上传文件的步骤 1.发送需要上传的文件信息给阿里网盘 返回 分片上传文件的列表 2.并发上传会导致文件乱码(顺序上传没有问题) 3.发送文件上传完成接口
> 
> 猜想:阿里网盘应该是对每次的文件端进行累加,而不是等文件片段上传完一起拼接
好吧,我自己再测试看看
