### ISSUE TITLE
能否提供一个openbsd编译版本

### ISSUE THREAD

**Issue by suselee** [LinkLeong/go-aliyundrive-webdav#17]
您好，我的路由器是openbsd7.0系统。
您是否可以提供一个编译好的openbsd版本包。
万分感激。

**Comment by LinkLeong** [comment]
已经新增,你可以试一下

**Comment by suselee** [comment]
> 已经新增,你可以试一下

可用，谢谢大佬！
在win10环境下用raidrive没有问题，有时间再用智能电视进行测试。
