### ISSUE TITLE
windows下rclone挂载修改文件夹名称失败

### ISSUE THREAD

**Issue by ssmmtt** [LinkLeong/go-aliyundrive-webdav#18]
![image](https://user-images.githubusercontent.com/16244320/142720200-7259c62f-d32f-4d15-b038-b97bb995a88a.png)

**Comment by LinkLeong** [comment]
Get it 。我抽空看一下，感谢反馈

**Comment by LinkLeong** [comment]
@ssmmtt 1.0.18已经修改该问题,兄弟可以试试,再有问题在反馈就好了.

**Comment by ssmmtt** [comment]
ok 棒棒哒！

**Comment by ssmmtt** [comment]
好多文件夹变成空的了，重启了程序也不行啊

**Comment by ssmmtt** [comment]
![image](https://user-images.githubusercontent.com/16244320/142751668-5975f263-f6d9-4e33-ab44-d6e3bb87deb9.png)
![image](https://user-images.githubusercontent.com/16244320/142751675-efef7708-25fa-4f61-850d-a92a1bd3a397.png)
![image](https://user-images.githubusercontent.com/16244320/142751681-42d7e73d-151d-4dde-9c59-01e1ded44e02.png)

**Comment by ssmmtt** [comment]
![image](https://user-images.githubusercontent.com/16244320/142751742-0c75ee49-d406-4763-9c92-7b95ac30d81b.png)
换回上个版本了🤣

**Comment by LinkLeong** [comment]
好吧,我在检查检查

**Comment by LinkLeong** [comment]
经过一顿操作,修复了,正在发布.

**Comment by ssmmtt** [comment]
牛逼！

**Comment by LinkLeong** [comment]
咋样兄弟   OK吗

**Comment by ssmmtt** [comment]
> 咋样兄弟 OK吗

很ok。
