### ISSUE TITLE
如何得知Token已经失效

### ISSUE THREAD

**Issue by iranee** [LinkLeong/go-aliyundrive-webdav#19]
阿里云盘的Token应该用不了1个月，如何得知Token已经失效，用那种方法可以检测到？
有没有可能加个类似 -check 的检测变量，如果发现Token实现，便于其他操作

**Comment by LinkLeong** [comment]
refreshToken的有效期应该是3天(预估),而token的有效期是7200秒.程序运行的时候会不停的更换token,来保证程序的可持续运行.不太清楚你的具体需求是什么?

**Comment by iranee** [comment]
我的意思是，如果refreshToken超过3天失效，怎么处理？手动填入新的refreshToken吗？

**Comment by LinkLeong** [comment]
程序已在运行的时候是不需要任何处理的,如果重启程序是需要手动填入新的refreshtoken.
还可以新建一个文件,里面放入refreshtoken,启动的时候-rt输入地址,这样程序会维护这个文件的refreshtoken,短时间重启也不需要refreshtoken.

或者你是想要一个检查token是否过期的命令???

**Comment by iranee** [comment]
对的，就是来检查token是否过期，以至于webdav什么时候断开了也不知道。

**Comment by iranee** [comment]
另外威联通的BUG什么时候可以修复下，我已经做成了插件，就差这个bug修复

**Comment by LinkLeong** [comment]
> 对的，就是来检查token是否过期，以至于webdav什么时候断开了也不知道。

这个好说,我尽快会添加

**Comment by LinkLeong** [comment]
> 另外威联通的BUG什么时候可以修复下，我已经做成了插件，就差这个bug修复

威联通这个比较麻烦,我还需要像朋友借机器,我尽快处理吧!

**Comment by LinkLeong** [comment]
> 对的，就是来检查token是否过期，以至于webdav什么时候断开了也不知道。

已添加-crt参数
