### ISSUE TITLE
用来同步时遇到的问题

### ISSUE THREAD

**Issue by togls** [LinkLeong/go-aliyundrive-webdav#20]
在 SwiftBackup 用 webdav 登录时会先发送 HEAD /SwiftBackup 测试文件是否存在。

但文件不存在，不会返回 NotFound。导致 SwiftBackup 不会初始化文件。

---

另一个问题

refresh token 时，更新失败（例如断网时，执行下面的命令）也会更新 token 文件，导致 token 文件被清空

```shell
./go-aliyun-webdav -rt=path/to/token/file
```

**Comment by togls** [comment]
我已经修复了

https://github.com/togls/go-aliyundrive-webdav

如果需要我可以创建一个 pull request

**Comment by LinkLeong** [comment]
> 我已经修复了
> 
> https://github.com/togls/go-aliyundrive-webdav
> 
> 如果需要我可以创建一个 pull request

可以的,你提就好了

**Comment by LinkLeong** [comment]
看到了解决的问题,感谢贡献
