### ISSUE TITLE
不显示目录

### ISSUE THREAD

**Issue by jwkinko** [LinkLeong/go-aliyundrive-webdav#24]
chrome 浏览器
不是根目录什么都不显示

根目录显示以下内容
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<D:multistatus xmlns:D="DAV:">
<D:response>
<D:href>/</D:href>
<D:propstat>
<D:prop>
<D:supportedlock>
<D:lockentry xmlns:D="DAV:">
<D:lockscope>
<D:exclusive/>
</D:lockscope>
<D:locktype>
<D:write/>
</D:locktype>
</D:lockentry>
</D:supportedlock>
<D:resourcetype>
<D:collection xmlns:D="DAV:"/>

**Comment by LinkLeong** [comment]
webdav协议本身不支持输出的,只是方便我调试我把代码打开了,后面可能会添加html供网页版使用

**Comment by jwkinko** [comment]
明白了，谢谢回复
