### ISSUE TITLE
Winwdows下执行提示RefreshToken Err=CreateFile

### ISSUE THREAD

**Issue by jasondong1999** [LinkLeong/go-aliyundrive-webdav#27]
我下载了windows的版本，执行怎么提示RefreshToken Err=CreateFile XXXXX: The system cannot find the file specified.

**Comment by LinkLeong** [comment]
你有穿参数吗,需要传-rt,麻烦截一下启动命令的图

**Comment by jasondong1999** [comment]
可以了，刚才忘了写“”，不好意思。
那个CMD命令框关了程序就关了吗？有没有办法一直运行啊

**Comment by LinkLeong** [comment]
我是用了一个脚本启动，然后设置开机启动脚本实现的，go程序我还不知道怎么弄成服务

**Comment by jasondong1999** [comment]
好的谢谢了，我测试了下上传跟下载速度有点慢啊。用WINDOWS直接挂载阿里云盘的程序上传速度快很多，但是那个程序不开源，没敢用。

**Comment by jasondong1999** [comment]
速度差了10倍左右，是有因为webdav的机制原因吗

**Comment by ethanchy** [comment]
你好，我也遇到了同样的问题，但是加了“”也没有解决
![image](https://user-images.githubusercontent.com/50769387/144840938-8451b20a-dddd-4c0e-a7fd-cd156fa06429.png)

**Comment by LinkLeong** [comment]
@ethanchy  感谢反馈,经过我测试确实存在问题,我已经修复了,正在发布.

**Comment by LinkLeong** [comment]
@ethanchy 更新了,你可以再试试

**Comment by ethanchy** [comment]
重新尝试之后在连接webdav的时候出现如下问题：
![image](https://user-images.githubusercontent.com/50769387/145057383-516fa94a-973d-449f-817c-132bf5354952.png)
![image](https://user-images.githubusercontent.com/50769387/145057478-46646221-216f-4c47-8ed1-3dd812cc6477.png)
