### ISSUE TITLE
新手咨询求助，用这个开了webdav后，怎么关闭呢

### ISSUE THREAD

**Issue by HedgingFight** [LinkLeong/go-aliyundrive-webdav#34]
新手咨询求助，用这个开了webdav后，怎么关闭呢。
开了这个后，是不是电脑就暴露在网络上了

**Comment by LinkLeong** [comment]
你是什么平台呢,这个是cmd命令,crat+c就停止了.应该不存在停止的情况吧.除非后台运行.

**Comment by HedgingFight** [comment]
> 

win10，开了webdav服务后，怎么用命令关闭呢。有开启对应是怎么关呢

**Comment by southcat** [comment]
win10你把窗口关了不就行了
