### ISSUE TITLE
win10下RaiDrive 需要https，怎么才能挂载？

### ISSUE THREAD

**Issue by bzadhere** [LinkLeong/go-aliyundrive-webdav#37]
RaiDrive 版本：2021.12.31

添加WebDav时，需要填写https地址：
[截图](https://i.getspace.eu/cloud/s/tAY67jaQPCHri3f)

**Comment by bzadhere** [comment]
<img src=https://i.getspace.eu/cloud/s/tAY67jaQPCHri3f>

**Comment by LinkLeong** [comment]
![image](https://user-images.githubusercontent.com/13556972/148325337-6915271e-2d15-460a-a137-dcbfafffc978.png)
这里不要勾上

**Comment by LinkLeong** [comment]
@bzadhere

**Comment by bzadhere** [comment]
谢谢
