### ISSUE TITLE
macos系统下，挂载网盘后，新建文件夹会不停的建立好多文件夹

### ISSUE THREAD

**Issue by xufenglong** [LinkLeong/go-aliyundrive-webdav#39]
**Describe the bug**<img width="301" alt="截屏2022-01-06 下午8 24 23" src="https://user-images.githubusercontent.com/59564514/148382632-427acc10-3d84-4181-82f2-5c9f4ab042e8.png">A clear and concise description of what the bug is.

**To Reproduce**<img width="301" alt="截屏2022-01-06 下午8 24 23" src="https://user-images.githubusercontent.com/59564514/148382632-427acc10-3d84-4181-82f2-5c9f4ab042e8.png">Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LinkLeong** [comment]
mac下是会有问题,建议使用工具挂载
