### ISSUE TITLE
登录云盘出错！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [LinkLeong/go-aliyundrive-webdav#9]
![image](https://user-images.githubusercontent.com/45259624/139571089-5e3bb9fa-25db-45bc-a4cf-d7e0d81e3959.png)

**Comment by LinkLeong** [comment]
@zxlhhyccc 没有做网页端的适配,需要通过工具连接才行

**Comment by ssmmtt** [comment]
挂载到本地就行了，网页的没啥用。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 没有做网页端的适配,需要通过工具连接才行

请问通过什么工具进行连接？能否做网页端的适配呢？

**Comment by ssmmtt** [comment]
![image](https://user-images.githubusercontent.com/16244320/139840950-0db96ad2-c24f-49d5-96f5-c5a9c76bfe0c.png)
windows下就用这两个，都不错。

**Comment by zxlhhyccc** [comment]
> 挂载到本地就行了，网页的没啥用。

请问怎么挂载到本地？烦请指教，谢谢！

**Comment by ssmmtt** [comment]
> > 挂载到本地就行了，网页的没啥用。
> 
> 请问怎么挂载到本地？烦请指教，谢谢！



> > 挂载到本地就行了，网页的没啥用。
> 
> 请问怎么挂载到本地？烦请指教，


> > 挂载到本地就行了，网页的没啥用。
> 
> 请问怎么挂载到本地？烦请指教，谢谢！
https://blog.csdn.net/weihongyicui/article/details/119566822
